# Generated by Django 3.2.6 on 2022-09-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='questions_pic'),
        ),
    ]
