# Generated by Django 3.2.6 on 2022-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='pic',
            field=models.ImageField(default=None, upload_to='themes_pic'),
        ),
    ]
