# Generated by Django 3.2.6 on 2022-09-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_theme_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='themes_pic'),
        ),
    ]
